# Generated by Django 3.2.9 on 2023-03-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_discipline', models.CharField(max_length=200, null=True, verbose_name='sub_discipline')),
                ('work_package_type', models.CharField(max_length=200, null=True, verbose_name='work_package_type')),
                ('project_phase', models.CharField(max_length=200, null=True, verbose_name='project_phase')),
                ('discipline', models.CharField(max_length=200, null=True, verbose_name='discipline')),
                ('activity_name', models.CharField(max_length=200, null=True, verbose_name='activity_name')),
                ('standard_activities_id', models.CharField(max_length=200, verbose_name='standard_activities_id')),
                ('predecessor', models.CharField(blank=True, max_length=200, verbose_name='predecessor')),
                ('relation', models.CharField(blank=True, max_length=200, verbose_name='relation')),
                ('lag', models.CharField(blank=True, max_length=200, verbose_name='lag')),
                ('duration', models.CharField(blank=True, max_length=200, verbose_name='duration')),
                ('physical_progress', models.CharField(blank=True, max_length=200, verbose_name='physical_progress')),
                ('financial_progress', models.CharField(blank=True, max_length=200, verbose_name='financial_progress')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='responsible')),
            ],
            options={
                'verbose_name': 'BD Standard Activities',
                'verbose_name_plural': 'BD Standard Activities',
                'db_table': 'db_standard_activities',
            },
        ),
        migrations.CreateModel(
            name='Wp_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_discipline', models.CharField(max_length=200, verbose_name='sub_discipline')),
                ('discipline', models.CharField(max_length=200, verbose_name='discipline')),
                ('sub_discipline_id', models.CharField(max_length=200, verbose_name='sub_discipline_id')),
            ],
            options={
                'verbose_name': 'BD Wp Types',
                'verbose_name_plural': 'BD Wp Types',
                'db_table': 'db_wp_type',
            },
        ),
    ]
