# Generated by Django 3.2.9 on 2021-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard_activities',
            options={'verbose_name': 'BD Standard Activities', 'verbose_name_plural': 'BD Standard Activities'},
        ),
        migrations.AlterModelOptions(
            name='wp_type',
            options={'verbose_name': 'BD Wp Types', 'verbose_name_plural': 'BD Wp Types'},
        ),
        migrations.AddField(
            model_name='standard_activities',
            name='activity_name',
            field=models.CharField(max_length=200, null=True, verbose_name='activity_name'),
        ),
        migrations.AddField(
            model_name='standard_activities',
            name='discipline',
            field=models.CharField(max_length=200, null=True, verbose_name='discipline'),
        ),
        migrations.AddField(
            model_name='standard_activities',
            name='project_phase',
            field=models.CharField(max_length=200, null=True, verbose_name='project_phase'),
        ),
        migrations.AddField(
            model_name='standard_activities',
            name='sub_discipline',
            field=models.CharField(max_length=200, null=True, verbose_name='sub_discipline'),
        ),
        migrations.AddField(
            model_name='standard_activities',
            name='work_package_type',
            field=models.CharField(max_length=200, null=True, verbose_name='work_package_type'),
        ),
        migrations.AlterField(
            model_name='standard_activities',
            name='physical_progress',
            field=models.CharField(blank=True, max_length=200, verbose_name='physical_progress'),
        ),
    ]
